### ISSUE TITLE
Breaks -sf and -sb of dmenu

### ISSUE THREAD

**Issue by ghost** [klaasb/passdmenu#3]
Hi! 

I just noticed that the arguments -sb (selection background) and -sf (selection foreground) are not passed to dmenu but interpreted as -s. 

`The password store location, f, does not exist.`

I tried working around by adding `-s mypasswordstorelocation` but that fails silently.

**Comment by klaasb** [comment]
Thanks for reporting!
This happens because I use [argparse](https://docs.python.org/3/library/argparse.html) and that allows grouping of short options, as well as -smypasswordlocation - that is, no space between short option and its argument.

Passing any unknown options to dmenu might not work if dmenu's options change at some point, or one wants to replace dmenu with something else, e.g. [rofi](http://davedavenport.github.io/rofi/), which also uses the -longoption style. So I added the -- separator, after which any arguments are passed to the menu.

E.g.: `passdmenu -uPt -D rofi -- -dmenu`

**Comment by ghost** [comment]
Thanks! :+1:
